project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "GD5302 - Health Data Science Practice"
  description: "Homepage for GD5302 - Health Data Science Practice."
  site-url: "https://maff1.github.io/website/"

  repo-url: https://github.com/maff1/website
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Marco Fernandes"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/maff1
        text: "GitHub organization"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Module information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: index.qmd
            text: Schedule
          - href: course-teachers.qmd
            text: Teachers
          - href: coursework.qmd
            text: Coursework
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    code-fold: true
    code-summary: "Show the code"
    toc: true

freeze: auto

editor: visual